### ISSUE TITLE
TypeScript and async/await support

### ISSUE THREAD

**Issue by Distortedlogic** [ledgerconnect/hivesigner.js#1]
TypeScript is the way and async/await is the future but actually the now.

**Comment by feruzm** [comment]
Exactly, we are rewriting SDK, UI and API. Stay tuned for update...

**Comment by Distortedlogic** [comment]
@feruzm First off, thanks for all the developing contributions to the community. I am the dev behind Memehub on Hive. I am currently rewriting the frontend/beckend. Can you provide a timeframe on when to expect a new release? My options are constrained for my aim on certain aspects. A timeframe would help a ton with my planning foreseeable development. Thanks!

**Comment by feruzm** [comment]
@Distortedlogic SDK update is probably couple days away, that will be rewritten in Typescript. UI+API update is month away. All changes will be backward compatible, so you can safely integrate current flow and I don't think your users will notice much changes except UI changes.

**Comment by feruzm** [comment]
@Distortedlogic We just pushed update to hivesigner sdk and moved to new repo: https://github.com/ecency/hivesigner-sdk
please check `hivesigner@3.2.2` version and see if everything works as expected, we are doing some more internal testing before announcing, but feel free to test this out, preferably **not** in production yet, until we do full test and announce new version. Closing this, if you find something, please create issue on new repo! Thanks!
